### ISSUE TITLE
Assistance with O'Gorman & Schneider Precipitation Scaling Code for Multi-Dimensional Data

### ISSUE THREAD

**Issue by chaithrast** [qnicolas/orographicPrecipitation#1]
Hi,

I hope this message finds you well. I am reaching out to seek your expertise regarding a challenge I am facing with precipitation scaling code using multi-dimensional data.

Currently, I am attempting to apply the O'Gorman & Schneider precipitation scaling code to my data, which includes latitude and longitude. However, I am encountering significant processing time issues due to the need to loop over the entire dataset, which is not practical given its size.

I have attempted parallelization as a potential solution to speed up the computations, but unfortunately, it has not been successful.

I am wondering if there might be a more efficient way to utilize the scaling code with multi-dimensional data. Is it possible to vectorize or parallelize the computations to improve performance? I would greatly appreciate any insights or suggestions you might have on how to approach this problem effectively.

Thank you very much for considering my inquiry.

Looking forward to hearing from you.

**Comment by qnicolas** [comment]
Sorry for replying so late! Indeed parallelization will most likely be the answer. Which functions exactly are you using? I haven't been using my OGorman/Schneider scaling codes in a long while.

What you will want to look at are the xarray+dask python packages (https://docs.xarray.dev/en/stable/user-guide/dask.html). If you can give me a more precise idea of the machine you're working on (number of cores, RAM) and the size/dimensions of your dataset (+ how it's stored, #files and format), I might be able to help you a bit more.
Cheers!
